HOTEL/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hotelapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotelapp/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url
from hotelapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'hotelapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Hotel.as_view(),name='hotel'),
    path('home/',views.Home.as_view(),name='home'),
    path('customer/',views.Table.as_view(),name='customer'),
    path('create/',views.Create,name='create'),
    path('Receipt/',views.Bill.as_view(),name='receipt'),
    re_path(r'^customer/(?P<pk>\d+)/$',views.Detail.as_view(),name='detail'),
    re_path(r'^Receipt/(?P<pk>\d+)/$',views.Receipt.as_view()),
    re_path(r'^update/(?P<pk>\d+)/$',views.Update.as_view(),name='update'),
    re_path(r'^delete/(?P<pk>\d+)/$',views.Delete.as_view(),name='delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hotelapp/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

# Create your models here.

class Manager(models.Model):
     name = models.CharField(max_length=256,blank=False)
     designation = models.CharField(max_length=25,blank=False)

     def __str__(self):
         return self.name



class Customer(models.Model):
     name = models.CharField(max_length=256,blank=False)
     age = models.PositiveIntegerField()
     checkin = models.DateTimeField(auto_now=True,blank=True)
     phoneno = models.PositiveIntegerField()
     idproof = models.ImageField()
     reporting = models.ForeignKey(Manager,on_delete=models.CASCADE)
     Choices = (
         ('Normal','NORMAL'),
         ('Ac','AC'),
         ('Non-ac','NON-AC'),
         ('Delux','DELUX'),
         ('Delux Pro','DELUX PRO'),
         ('Super Delux','SUPER DELUX'),
         ('Suite','SUITE')
    )
     room = models.CharField(max_length=25,choices=Choices,null=True)
     Select = (
         ('net banking','Net banking'),
         ('debit card','Debit Card'),
         ('credit card','Credit Card'),
         ('paytm','PayTm')
     )
     payment_mode = models.CharField(max_length=20,choices=Select,null=True)

     def __str__(self):
         return self.name

     def get_absolute_url(self):
         return reverse('hotelapp:detail',kwargs={'pk':self.pk})

hotelapp/forms.py
from django import forms
from .models import Customer
from datetime import datetime

class CustomerForm(forms.ModelForm):
     name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
     age = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control'}))
     phoneno = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control'}))
     idproof = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control'}))

     class Meta():
        model = Customer
        fields = ('name','age','phoneno','idproof','room','payment_mode','reporting')

hotelapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from .models import Customer,Manager
from django.views.generic import( TemplateView,ListView,CreateView,DetailView,DeleteView,UpdateView)
from .forms import CustomerForm
# Create your views here.

class Bill(ListView):
    template_name = 'receipt.html'
    model = Customer

class Receipt(DetailView):
    template_name = 'bill.html'
    model = Customer

class Hotel(TemplateView):
    template_name = 'hotel.html'

class Home(TemplateView):
    template_name = 'home.html'

class Table(ListView):
    model = Customer
    template_name = 'table.html'

def Create(request):
    form = CustomerForm()
    if request.method == 'POST':
        form = CustomerForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('hotelapp:customer'))
        else:
            return HttpResponse("<h2>INVALID DATA</h2>")
    else:
        return render(request,'create.html',{'form':form})


class Detail(DetailView):
    model = Customer
    template_name = 'detail.html'

class Update(UpdateView):
    model = Customer
    template_name = 'update.html'
    fields = ['name','age','phoneno']

#def updateconfirm(request):
#    return render(request,'Uconfirm.html')

class Delete(DeleteView):
    model = Customer
    template_name = 'delete.html'
    success_url = reverse_lazy('hotelapp:customer')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>

        a:hover
          {
            text-decoration: None;
          }
    </style>


    </head>
<body>

<div class="container-fluid">
    <div class="alert alert-info" >
        <a href="{% url 'hotelapp:hotel' %}" class="alert-link" role="button" style="font-size:14px">HotelTaj</a>
        <a href="{% url 'hotelapp:home' %}" class="alert-link" role="button" style="font-size:14px">&nbsp;&nbsp;&nbsp;Home</a>
        <a href="{% url 'hotelapp:customer' %}" class="alert-link" role="button" style="font-size:14px">&nbsp;Customers</a>
        <a href="{% url 'hotelapp:receipt' %}" class="alert-link" role="button" style="font-size:14px">&nbsp;&nbsp;Receipt</a>
        <a href="{% url 'admin:index' %}" class="alert-link" role="button" style="font-size:14px">&nbsp;&nbsp;Admin</a>&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <a href="{% url 'hotelapp:create' %}"> <button type="button" class="btn btn-success">Add User</button></a>
    </div>
</div>
</body>
{% block content %}
{% endblock %}
</html>

templates/bill.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bills</title>
</head>
<body>
<div class="container">
<h4>Receipt of {{customer.name}}</h4>
<h5>Room:: {{customer.room}}</h5>
<h5>Payment Status::Paid</h5>
</div>
</body>
</html>
{% endblock %}

templates/confirm.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>{{ from.name }}</h3>
    <h3>{{ from.name }}</h3>
    <h3>{{ from.name }}</h3>
    <h3>{{ from.name }}</h3>
    <input type="submit" value="Submit">
</form>
</body>
{% endblock %}
</html>

templates/create.html
{% extends 'base.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<div class="container">
    <div class="jumbotorn">
        <form method="POST" enctype="multipart/form-data" class="form-horizontal">
        <div class="form-header">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-md-4">{{form.as_p}}</div></div><br/>
        <input type="submit" value="Submit" class="btn btn-warning">&nbsp;&nbsp;
        <input type="reset" value="Clear" class="btn btn-info">
        </div>
    </form>
    </div>
</div>

</body>

{% endblock %}
</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To Delete</title>
</head>
<body>
  <div class="container">

   <form method="post" enctype="multipart/form-data">
       <h2>Are You Sure To Delete  "{{customer.name}}" Profile ???</h2><br/>
     {% csrf_token %}
     {{form.as_p}}
     <input type="submit" value="Yes DELETE" class="btn btn-info">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

      <a href="{% url 'hotelapp:customer' %}"><button type="button" class="btn btn-success" >No CANCEL</button></a>
   </form>
  </div>
</body>
{% endblock %}
</html>

templates/detail.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<div class="container" align="center">
    <div class="jumbotorn">
    <h2>Details of {{customer.name}} is ::</h2>
    <img src="{{customer.idproof.url}}" width="420" height="230" align="center">
        <em><h3>ID::{{customer.id}}</h3></em>
    <em><h3>Name::{{customer.name}}</h3></em>
<em><h3>Age::{{customer.age}}</h3></em>
<em><h3>Checkin::{{customer.checkin}}</h3></em>
    <em><h3>PhoneNO::{{customer.phoneno}}</h3></em>
<em><h3>Reporting::{{customer.reporting}}</h3></em>
    <a href="{% url 'hotelapp:update' pk=customer.id %}"><button type="button" class="btn btn-info">UPDATE</button></a>&nbsp;&nbsp;&nbsp;
    <a href="{% url 'hotelapp:delete' pk=customer.id %}"><button type="button" class="btn btn-danger">DELETE</button></a><br/><br/>
   </div>
</div>


</body>
{% endblock %}
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<html>
{% load staticfiles %}
<head>
    <style>
      h2
       {

         color:blue;
       }
    </style>
</head>
<body>
<div class="container-fluid">
    <h2>Journey to TAJ Pandoras</h2>
    <img src="{% static 'image/hotel5.png' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel4.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel2.jpg' %}" alt="No Image" width="367px" height="210px"><br/><br/>
    <img src="{% static 'image/hotel1.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel7.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel8.jpg' %}" alt="No Image" width="367px" height="210px"><br/><br/>
    <img src="{% static 'image/hotel9.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel10.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel512.jpg' %}" alt="No Image" width="367px" height="210px"><br/><br/>
    <img src="{% static 'image/hotel13.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel14.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel511.jpg' %}" alt="No Image" width="367px" height="210px"><br/><br/>
    <img src="{% static 'image/hotel20.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel17.jpg' %}" alt="No Image" width="367px" height="210px">&nbsp;&nbsp;&nbsp;&nbsp;
    <img src="{% static 'image/hotel18.jpg' %}" alt="No Image" width="367px" height="210px">



</div>
</body>
{% endblock %}
</html>

templates/hotel.html
{% extends 'base.html' %}

{% block content %}
<html>
{% load staticfiles %}
<head>
    <style>
    h2
      {
        text-decoration:underline;
      }

</style>
</head>
<body>
<div class="container-fluid">
<h1>Welcome to TAJ PALACE </h1>
<img src="{% static 'image/hotel6.jpg' %}" alt="Sorry no image" width="1200px" height="300px"><br/>
<h4>Taj is a chain of luxury hotels and a subsidiary of the Indian Hotels Company
    Limited - headquartered at Express Towers, Nariman Point in Mumbai. Incorporated
    by the founder of the Tata Group, Jamsetji Tata, in 1903, the company is a part
    of the Tata Group, one of India's largest business conglomerates.</h4>

    <h2>History</h2>
    <h4>In 1974, the group opened India's first international five star deluxe beach resort,
         the Fort Aguada Beach Resort in Goa. In 1970s, the Taj Group also began its business
         in metropolitan hotels, opening the five-star deluxe hotel, Taj Coromandel in Chennai,
         in 1974, acquiring an equity interest and operating contract for the Taj President
         (now Vivanta by Taj - President), a business hotel in Mumbai, in 1977, and also opening
         the Taj Mahal Hotel in Delhi in 1978.
         The group has been converting royal palaces in India into luxury hotels since the 1970s.
         The first palace to be converted into a Taj luxury hotel was the Lake Palace in Udaipur,
         in 1971. Other examples include the Rambagh Palace in Jaipur, Umaid Bhawan Palace in Jodhpur,
         Falaknuma Palace in Hyderabad and Nadesar Palace in Varanasi.
         Concurrently with the expansion of its luxury hotel chain in the major metropolitan cities,
         the Taj Group also expanded its business hotels division in the major metropolitan and large
         secondary cities in India. During the 1990s, the Taj Group continued to expand its geographic
         and market coverage in India. It developed specialized operations (such as wildlife lodges)
         and consolidated its position in established markets through the upgrading of existing properties
         and development of new properties. Taj also set up the Taj Kerala Hotels and Resorts Limited
         in the early 1990s along with the Kerala Tourism Development Corporation. Ten hotels of the
         Taj group are members of the Leading Hotels of the World..</h4>

    <h2>Notable hotels</h2>
    <h4>Two hotels of the Taj group, namely Rambagh Palace in Jaipur and the Taj Mahal Palace
        & Tower in Mumbai, were ranked in 2013 by Condé Nast Traveler among its "Top 100 Hotels
        and Resorts in the World".[12] In late 2013, the Indian Traveller magazine ranked Taj
        Lake Palace in Udaipur and Taj Exotica Resort & Spa in Maldives as numbers 34 and 98,
        respectively, on its list of "100 Best Hotels & Resorts".[13] Condé Nast Traveler also
        ranked the Taj Mahal Palace in Mumbai as number 13 on its list of "Gold Standard Hotels"
        in 2014.[14] In 2005, a famous luxury hotel in New York city, The Pierre was acquired.
    </h4>


</div>
</body>
{% endblock %}
</html>

templates/receipt.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Receipt</title>
</head>
<body>
<div class="container">
<table class="table table-striped"><tr>
    <th>Name</th>
     </tr>
    {% for rec in customer_list %}
    <tr><td>{{rec.name}}</td>
        <td><a href="{{rec.id}}">check</a></td> </tr>
    {% endfor %}



</table>
</div>
</body>
</html>
{% endblock %}

templates/table.html
{% extends 'base.html' %}
<html>

{% block content %}
<body>
<div class="container-fluid">
<br/><br/>
<table  class="table table-hover">
    <tr class="info">
    <th scope="col">ID</th>
    <th scope="col">Name</th>
    <th scope="col">Age</th>
        <th scope="col">Checkin</th>

        <th scope="col">View</th></tr>
    {% for person in customer_list %}
    <tr><td>{{person.id}}</td>
        <td>{{person.name}}</td>
        <td>{{person.age}}</td>
        <td>{{person.checkin}}</td>
        <td><a href="{{person.id}}">Details</a></td>
    </tr>
    {% endfor %}
</table>
</div>
</body>

{%  endblock  %}
</html>

templates/update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    //<style>
      //  input{
        //     width:10%;
          // }
    //</style>
</head>
<body>
<div class="container">
<form method="post" enctype="multipart/form-data" class="form-horizontal">
    <div class="form-group">
        <div class="col-sm-3">{{form.as_p}}</div></div>
    {% csrf_token %}
    <input type="submit" value="UPDATE" class="btn btn-success"><br/>
</form>
</div>
</body>
 {% endblock %}
</html>